

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

; Define a velocidade (ajuste conforme seu Serial.begin)
monitor_speed = 115200

; Ativa o modo de enviar apenas ao apertar Enter
monitor_filters = send_on_enter

; (Opcional) Mostra o que você está digitando
monitor_echo = yes

; (Opcional) Define o final de linha (LF ou CRLF)
monitor_eol = LF


lib_deps =
    adafruit/RTClib
    olikraus/U8g2
    adafruit/Adafruit BME280 Library
    greiman/SdFat@^2.3.1
